export const CUS_LOGIN_REQUEST = "CUS_LOGIN_REQUEST";
export const CUS_LOGIN_SUCCESS = "CUS_LOGIN_SUCCESS";
export const CUS_LOGIN_FAIL = "CUS_LOGIN_FAIL";
export const CUS_LOGOUT = "CUS_LOGIN_LOGUT";


export const CUS_REGISTER_REQUEST = "CUS_REGISTER_REQUEST";
export const CUS_REGISTER_SUCCESS = "CUS_REGISTER_SUCCESS";
export const CUS_REGISTER_FAIL = "CUS_REGISTER_FAIL";
