export const GET_CART_ITEMS_REQUEST = "GET_CART_ITEMS_REQUEST"
export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS"
export const GET_CART_ITEMS_FAIL = "GET_CART_ITEMS_FAIL"

export const GET_CART_ITEMS_DETAILS_REQUEST = "GET_CART_ITEMS_DETAILS_REQUEST"
export const GET_CART_ITEMS_DETAILS_SUCCESS = "GET_CART_ITEMS_DETAILS_SUCCESS"
export const GET_CART_ITEMS_DETAILS_FAIL = "GET_CART_ITEMS_DETAILS_FAIL"
export const GET_CART_ITEMS_DETAILS_RESET = "GET_CART_ITEMS_DETAILS_RESET"